version: v1.0
name: MaestroCI Builder
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu2004

blocks:
  - name: Static Site Builder
    task:
      jobs:
      - name: Job
        commands:
          - checkout
          - git submodule update --init --recursive
          - git clone https://github.com/baalajimaestro/personal-website -b master $HOME/public
          - docker build . -t ci
          - docker run -v $(pwd):/app -v $HOME/public:/public -e GH_PERSONAL_TOKEN=${GH_PERSONAL_TOKEN} ci
      secrets:
        - name: api-keys